FreewayIsuzu/FreewayIsuzu/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreewayIsuzu.Controllers
{
    public class ContactController : BaseController
    {
        public ActionResult DealerInfo()
        {
            return View(@"~/Views/Contact/DealerInfo.cshtml");
        }

        public ActionResult Fleet()
        {
            return View(@"~/Views/Contact/Fleet.cshtml");
        }

    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/FinanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreewayIsuzu.Controllers
{
    public class FinanceController : BaseController
    {
        public ActionResult Index()
        {
            return View(@"~/Views/Finance/Index.cshtml");
        }
        
        public ActionResult Quote()
        {
            return View(@"~/Views/Finance/Quote.cshtml");
        }
        
        public ActionResult TestDrive()
        {
            return View(@"~/Views/Finance/TestDrive.cshtml");
        }
    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/LocatorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreewayIsuzu.Controllers
{
    public class LocatorController : BaseController
    {
        public ActionResult TruckLocator()
        {
            return View(@"~/Views/Locator/TruckLocator.cshtml");
        }

    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/ShowroomController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreewayIsuzu.Controllers
{
    public class ShowroomController : BaseController
    {
        public ActionResult Index()
        {
            return View(@"~/Views/Showroom/Index.cshtml");
        }

        public ActionResult Detail(string viewName)
        {
            return View(viewName);
        }
    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreewayIsuzu.Controllers
{
    public class VehicleController : BaseController
    {
        public ActionResult Value()
        {
            return View(@"~/Views/Vehicle/Value.cshtml");
        }
    }
}

FreewayIsuzu/FreewayIsuzu/Views/Shared/_Brand.cshtml
<div id="brand">
	<div class="brand-wrap">
		Powered by <a target="_blank" href="http://vincontrol.com"
			style="color: white;">V<span style="color: red;">I</span>N
		</a> | VINControl LLC. <br /> <span
			style="font-size: .85em !important; color: #aaaaaa !important;">While
			every effort is made to ensure the accuracy of this site's content,
			we are not responsible for any errors in pricing or advertisements on
			this site. Please check with the sales department to confirm any
			information seen on this page.</span>
	</div>
</div>

FreewayIsuzu/FreewayIsuzu/Views/Shared/_ContactForm.cshtml
<script type="text/javascript" src="/Scripts/js/pages/pc_validation.js"></script>
<div id="tertiary-contact">
    <div id="tertiary-contact-wrapper">
        <form class="validate" id="tertiary-form" action="" method="post">
            <fieldset>
                <legend id="form-header" style="border: none; line-height: 80%; padding-bottom: 10px; padding-top: 8px;margin-bottom: 10px;">
                    <span style="font-size: .7em;">Have a Question?</span>
                    <br />
                    Contact Us!
                </legend>
                <div id="error"></div>
                <div class="input-prepend control-group">
                    <span class="add-on"><i class="icon-user"></i></span>
                    <input maxlength="50" name="name" class="required" id="fname" type="text" placeholder="First Name" title="First Name" />
                </div>
                <div class="input-prepend control-group">
                    <span class="add-on"><i class="icon-user"></i></span>
                    <input name="name" maxlength="50" class="required" id="lname" type="text" placeholder="Last Name" title="Last Name" />
                </div>
                <div class="input-prepend control-group">
                    <span class="add-on"><i class="icon-envelope"></i></span>
                    <input name="email" maxlength="50" class="required" id="email" type="text" placeholder="Email" title="Email" />
                </div>
                <div class="input-prepend control-group">
                    <span class="add-on"><b style="color: black !important;">#</b></span>
                    <input name="phone" class="number required" id="phone" type="text" value="999-999-9999" title="Phone number" />
                </div>
                <div class="input-prepend control-group">
                    <textarea name="comments" maxlength="3000" id="comments" placeholder="Add Comments" title="Comments"></textarea>
                </div>

                <div id="submitFormLoading">
                    <div id="submitFormLoadingText">*Sending...</div>
                    
                </div>
                <input type="button" style="width: 100%" name="send" id="send" value="Submit" />
            </fieldset>
        </form>
    </div>
</div>

FreewayIsuzu/FreewayIsuzu/Views/Shared/_DealerInfo.cshtml
<div id="dealerInfo">
	<h4>Business Hours</h4>
	<ul class="unstyled">
		<li>
			<div style="width: 75px; display: inline-block;">Weekdays:</div> 9am - 6pm
		</li>
		<li>
			<div style="width: 75px; display: inline-block;">Saturday:</div> 9am - 6pm
		</li>
		<li>
			<div style="width: 75px; display: inline-block;">Sunday:</div> By Appointment Only
		</li>
	</ul>
</div>

FreewayIsuzu/FreewayIsuzu/Views/Shared/_Footer.cshtml
<div class="row">
	<!-- FOOTER ROW -->
	<div class="span12" id="spanFooter">
		<div id="footer">
			<div id="footer-wrap">
				Freeway Isuzu &copy; 2012 - 2014 | 1655 West 6th Street Suite #111 Corona, CA 92882 <br>
			</div>
		</div>
	</div>
</div>

FreewayIsuzu/FreewayIsuzu/Views/Shared/_Header.cshtml
<div id="menu-holder">
    <div class="mn-home menu-items">
        <a href="/">HOME</a>
    </div>

    <div class="mn-specials menu-items hasMenu">
        <a>SPECIALS <b class="caret"> </b></a><br/>
        <div class="arrow-holder">
			
        </div>
        <div class="menu-holder">
            <a href="@Url.Action("VehicleSpecials","Specials")" class="menu-holder-links">Vehicle Specials</a>
            <a href="@Url.Action("Lease","Specials")" class="menu-holder-links">Lease &amp; Finance Offers</a>
            <a href="@Url.Action("Service","Specials")" class="menu-holder-links">Service Specials</a>
            <a href="@Url.Action("Parts","Specials")" class="menu-holder-links">Parts Specials</a>
        </div>
    </div>

    <div class="mn-new menu-items hasMenu">
        <a>NEW <b class="caret"> </b></a><br/>
        <div class="arrow-holder">
			
        </div>
        <div class="menu-holder">
            <a href="@Url.Action("NewCars","Inventory")" class="menu-holder-links">Inventory</a>
            <a href="@Url.Action("Index","Showroom")" class="menu-holder-links">Showroom</a>
            <a href="@Url.Action("Value","Vehicle")" class="menu-holder-links">Value My Trade</a>
            <a href="@Url.Action("Index","Comparison")" class="menu-holder-links">Competitive Comparison</a>
            <a href="@Url.Action("TruckLocator","Locator")" class="menu-holder-links">New Truck Locator</a>
			
        </div>
    </div>

    <div class="mn-used menu-items hasMenu">
        <a>PRE-OWNED <b class="caret"> </b></a><br/>
        <div class="arrow-holder">
			
        </div>
        <div class="menu-holder">
            <a href="@Url.Action("UsedCars","Inventory")" class="menu-holder-links">Inventory</a>
            <a href="@Url.Action("Value","Vehicle")" class="menu-holder-links">Value My Trade</a>
            <a href="@Url.Action("TruckLocator","Locator")" class="menu-holder-links">Pre-Owned Truck Locator</a>
        </div>
    </div>

    <div class="mn-sale-finance menu-items hasMenu">
        <a>SALES &amp; FINANCE <b class="caret"> </b></a><br/>
        <div class="arrow-holder">
			
        </div>
        <div class="menu-holder" style="width: 167px;">
            <a href="@Url.Action("Quote","Finance")" class="menu-holder-links">Request A Quote</a>
            <a href="@Url.Action("Index","Finance")" class="menu-holder-links">Finance App</a>
            <a href="@Url.Action("TestDrive","Finance")" class="menu-holder-links">Test Drive</a>
        </div>
    </div>

    <div class="mn-fleet menu-items hasMenu">
        <a>FLEET <b class="caret"> </b></a><br/>
        <div class="arrow-holder">
			
        </div>
        <div class="menu-holder" style="width: 145px;height: 27px;">
            <a href="@Url.Action("Fleet","Contact")" class="menu-holder-links">Fleet Info</a><br/>
        </div>
    </div>

    <div class="mn-service-part menu-items hasMenu">
        <a>SERVICE &amp; PARTS <b class="caret"> </b></a><br/>
        <div class="arrow-holder">
			
        </div>
        <div class="menu-holder" style="width: 170px;">
            <a href="@Url.Action("ServiceInfo","ServiceParts")" class="menu-holder-links">Service Department</a>
            <a href="@Url.Action("Retail","ServiceParts")" class="menu-holder-links">Parts Department</a>
        </div>
    </div>

    <div class="mn-dealer-contact menu-items hasMenu">
        <a>DEALER INFO &amp; CONTACT <b class="caret"> </b></a><br/>
        <div class="arrow-holder">
			
        </div>
        <div class="menu-holder" style="width: 162px;">
            <a href="@Url.Action("DealerInfo","Contact")" class="menu-holder-links">Hours &amp; Info</a>
            <!-- <a href="/employment" class="menu-holder-links">Employment</a> -->
        </div>
    </div>

</div>


FreewayIsuzu/FreewayIsuzu/Views/Shared/_Layout.cshtml
@using System.Configuration
@using FreewayIsuzu.Handlers
<!DOCTYPE html>
<html lang="en">
<head>
    @RenderSection("meta", required: false)
    @*<meta name="keywords" content="new trucks, used trucks, truck, trucks, commercial vehicles, parts specials, service specials, value trade, Good prices, Freeway Isuzu" />*@
    <meta name="author" content="freewayisuzutruck.com, freewayisuzu.com, freewayisuzu" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title | Freeway Isuzu Truck</title>
    <link rel="icon" type="image/png" href="/Content/images/fv_icon_1.png" />
    @Styles.RenderFormat("<link href=\"{0}\" type=\"text/css\" rel=\"stylesheet\"/>", "~/bundles/commoncss")
    @*<script src="~/Scripts/js/owlcarousel/jquery.min.js"></script>*@
    @*<script src="~/Scripts/libraries/jquery-2.1.1.min.js"></script>*@
    @Scripts.RenderFormat("<script type=\"text/javascript\" src=\"{0}\"></script>", "~/bundles/newJquery")
    <script src="~/Scripts/js/owlcarousel/owl.carousel.min.js"></script>
    <link href="~/Scripts/js/owlcarousel/owl.carousel.min.css" rel="stylesheet"/>
    <link href="~/Scripts/js/owlcarousel/owl.theme.default.css" rel="stylesheet"/>
    @Scripts.RenderFormat("<script type=\"text/javascript\" src=\"{0}\"></script>", "~/bundles/jquerylib")
    @*<script src="~/Scripts/js/bxSlider/jquery.bxslider.min.js"></script>
    <link href="~/Scripts/js/bxSlider/jquery.bxslider.css" rel="stylesheet" />*@
    @*<script src="~/Scripts/js/jquery.bxSlider.js"></script>*@
    @*<script src="~/Scripts/js/owlcarousel/jquery.min.js"></script>*@
    
    <style>
        span#phone h2 { color: #fff !important; }
        td.gsc-search-button { width: 0% !important; }
        #ocational-carousel .item
        {
            margin: 0px;
            padding: 0px;
            border-radius: 10px;
            overflow: hidden;
            text-align: center;
            position: relative;
            cursor: pointer;
            background: #fff;
            border: 3px solid #fff;
            font-weight: bold;
            font-size: 15px;
            -webkit-transition: background .2s ease-out;
            -moz-transition: background .2s ease-out;
            -o-transition: background .2s ease-out;
            transition: background .2s ease-out;
        }

            #ocational-carousel .item .body-type
            {
                background-color: transparent;
            }

            #ocational-carousel .item img
            {
                width: 100%;
            }

        #owl-carousel .owl-item img
        {
            display: block;
            width: 100%;
            -webkit-transform-style: preserve-3d;
        }

        #ocational-carousel .item .body-type-hover
        {
            opacity: 0;
            -webkit-transition: all .2s ease-out;
            -moz-transition: all .2s ease-out;
            -o-transition: all .2s ease-out;
            transition: all .2s ease-out;
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
        }

        #ocational-carousel .item:hover
        {
            background: #ddd;
            
        }

            #ocational-carousel .item:hover .body-type-hover
            {
                opacity: 1;

            }

        #ocational-carousel .item span
        {
            position: absolute;
            bottom: 0px;
            margin: 0 auto;
            left: 0;
            right: 0;
            color: black;
        }

        .owl-carousel .owl-dot, .owl-carousel .owl-nav .owl-next, .owl-carousel .owl-nav .owl-prev
        {
            cursor: pointer;
            cursor: hand;
            -webkit-user-select: none;
            -khtml-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        .owl-next
        {
            right: -30px;
        }

            .owl-next:before
            {
                font-family: 'FontAwesome';
                /*content: "";*/
            }

        .owl-prev
        {
            left: -30px;
        }

            .owl-prev:before
            {
                font-family: 'FontAwesome';
                /*content: "";*/
            }

        .owl-prev, .owl-next
        {
            position: absolute;
            top: 37%;
            color: #aaa;
            font-size: 35px;
            -webkit-transition: all .2s ease-out;
            -moz-transition: all .2s ease-out;
            -o-transition: all .2s ease-out;
            transition: all .2s ease-out;
        }
    </style>
</head>
<body>
    <div class="container" id="wrapper">
        <!-- WRAPPER DIV -->
        <div id="fb-root"></div>

        <script type="text/javascript">
            var dealerId = 37695;
        </script>
        <!-- HEADER ROW -->
        @{ Html.RenderPartial("~/Views/Shared/_Title.cshtml"); }
        <!-- HEADER END -->
        <!-- NAVBAR ROW -->
        @{ Html.RenderPartial("~/Views/Shared/_Header.cshtml"); }
        <!-- NAVBAR END -->
        @{ Html.RenderPartial("~/Views/Shared/_BodyStyles.cshtml"); }
        @RenderBody()
    </div>
    <!-- END OF WRAPPER DIV -->
    <!-- BRAND ROW -->
    @{ Html.RenderPartial("~/Views/Shared/_Brand.cshtml"); }
    <!-- END OF BRAND ROW -->
    <!-- alert for success submitsion -->
    <div id="alert_success" style="bottom: 0px; top: 0px; position: absolute; z-index: 10000; width: 100%; height: 100%; display: none;">
        <label style="font-size: 20px; color: green; margin-left: 39%; margin-top: 20%; font-style: italic;" id="lb-sending">Sending your information!</label>
        <label style="font-size: 20px; color: green; margin-left: 39%; margin-top: 20%; font-style: italic;" id="lb-success">Your information has been submitted successfully!</label>
    </div>
    <!-- end -->
    @*@Scripts.Render("~/bundles/jquery")
      @RenderSection("scripts", required: false)*@
    <div id="resSuccess">
        <div id="resSuccessContent">Success!</div>
    </div>
    <div id="resBackToTop">
        <div id="resBackToTopBtn"></div>
    </div>

    <div id="resTopMenus">
        <div id="topMenuBtn"></div>
    </div>
    <div id="resMenuHolder">
        <div class="resMenuItems">
            <div class="resMenuHeader">
                <div class="resMenuTitle">SPECIALS</div>
                <div class="resMenuExpand">+</div>
            </div>
            <div class="resMenuLinks">
                <a href="@Url.Action("VehicleSpecials", "Specials")" class="menu-holder-links">Vehicle Specials</a>
                <a href="@Url.Action("Lease", "Specials")" class="menu-holder-links">Lease &amp; Finance Offers</a>
                <a href="@Url.Action("Service", "Specials")" class="menu-holder-links">Service Specials</a>
                <a href="@Url.Action("Parts", "Specials")" class="menu-holder-links">Parts Specials</a>
            </div>
        </div>

        <div class="resMenuItems">
            <div class="resMenuHeader">
                <div class="resMenuTitle">NEW</div>
                <div class="resMenuExpand">+</div>
            </div>
            <div class="resMenuLinks">
                <a href="@Url.Action("NewCars", "Inventory")" class="menu-holder-links">Inventory</a>
                <a href="@Url.Action("Index", "Showroom")" class="menu-holder-links">Showroom</a>
                <a href="@Url.Action("Value", "Vehicle")" class="menu-holder-links">Value My Trade</a>
                <a href="@Url.Action("Index", "Comparison")" class="menu-holder-links">Competitive Comparison</a>
                <a href="@Url.Action("TruckLocator", "Locator")" class="menu-holder-links">New Truck Locator</a>
            </div>
        </div>

        <div class="resMenuItems">
            <div class="resMenuHeader">
                <div class="resMenuTitle">PRE-OWNED</div>
                <div class="resMenuExpand">+</div>
            </div>
            <div class="resMenuLinks">
                <a href="@Url.Action("UsedCars", "Inventory")" class="menu-holder-links">Inventory</a>
                <a href="@Url.Action("Value", "Vehicle")" class="menu-holder-links">Value My Trade</a>
                <a href="@Url.Action("TruckLocator", "Locator")" class="menu-holder-links">Pre-Owned Truck Locator</a>
            </div>
        </div>

        <div class="resMenuItems">
            <div class="resMenuHeader">
                <div class="resMenuTitle">SALES &amp; FINANCE</div>
                <div class="resMenuExpand">+</div>
            </div>
            <div class="resMenuLinks">
                <a href="@Url.Action("Quote", "Finance")" class="menu-holder-links">Request A Quote</a>
                <a href="@Url.Action("Index", "Finance")" class="menu-holder-links">Finance App</a>
                <a href="@Url.Action("TestDrive", "Finance")" class="menu-holder-links">Test Drive</a>
            </div>
        </div>

        <div class="resMenuItems">
            <div class="resMenuHeader">
                <div class="resMenuTitle">FLEET</div>
                <div class="resMenuExpand">+</div>
            </div>
            <div class="resMenuLinks">
                <a href="@Url.Action("Fleet", "Contact")" class="menu-holder-links">Fleet Info</a>
            </div>
        </div>

        <div class="resMenuItems">
            <div class="resMenuHeader">
                <div class="resMenuTitle">SERVICE &amp; PARTS</div>
                <div class="resMenuExpand">+</div>
            </div>
            <div class="resMenuLinks">
                <a href="@Url.Action("ServiceInfo", "ServiceParts")" class="menu-holder-links">Service Department</a>
                <a href="@Url.Action("Retail", "ServiceParts")" class="menu-holder-links">Parts Department</a>
            </div>
        </div>

        <div class="resMenuItems">
            <div class="resMenuHeader">
                <div class="resMenuTitle">DEALER INFO &amp; CONTACT</div>
                <div class="resMenuExpand">+</div>
            </div>
            <div class="resMenuLinks">
                <a href="@Url.Action("DealerInfo", "Contact")" class="menu-holder-links">Hours &amp; Info</a>
            </div>
        </div>
    </div>

    <div id="resOverlay"></div>

<script src="/Scripts/js/pages/pc_common.js" type="text/javascript"></script>
<script>
    $(document).ready(function() {
        //$(".bxslider").bxSlider({
        //    minSlides: 5,
        //    maxSlides: 5,
        //    slideWidth: 295,
        //    //moveSlides: 5,
        //    pager: false
        //});
        //$(".owl-carousel").owlCarousel();
        $(".owl-carousel").owlCarousel({
            items: 5,
            loop: true,
            margin: -5,
            merge: true,
            nav: false,
            navText: ["<", ">"],
            autoplay: true,
            //autoplayTimeout: 1000,
            autoplayHoverPause: true,
            slideSpeed: 3000,
            dots: true,
            responsiveClass: true,
            responsive: {
                320: {
                    items: 2
                },
                768: {
                    items: 3
                },
                1024: {
                    items: 5,
                    mergeFit: true
                }
            }
        });
    });
</script>
    <script>
        var DealerEmail = "@SessionHandler.Dealer.Email";
        var FreewayIsuzuWebURL = "@ConfigurationManager.AppSettings["freewayisuzu:WebURL"]";
        $('.dropdown-toggle').dropdown(); (function (d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id))
                return;
            js = d.createElement(s);
            js.id = id;
            js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=83806641846";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>

    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-29548246-2']);
        _gaq.push(['_setDomainName', 'freewayisuzu.com']);
        _gaq.push(['_setAllowLinker', true]);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script');
            ga.type = 'text/javascript';
            ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(ga, s);
        })();

    </script>

    <script>
        (function () {
            var cx = '012348914479498806846:tghu2_k16ii';
            var gcse = document.createElement('script');
            gcse.type = 'text/javascript';
            gcse.async = true;
            gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
                '//www.google.com/cse/cse.js?cx=' + cx;
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(gcse, s);
        })();
    </script>
    <gcse:search></gcse:search>
</body>

</html>

FreewayIsuzu/FreewayIsuzu/Views/Shared/_Map.cshtml
<div id="map">
	<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3312.358767915771!2d-117.5984211!3d33.880412899999996!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xf2b9b4fd43504cde!2sFreeway+Isuzu!5e0!3m2!1sen!2s!4v1393903726428" width="100%" height="295" frameborder="0" style="border:0"></iframe>
</div>

FreewayIsuzu/FreewayIsuzu/Views/Shared/_Title.cshtml
@using FreewayIsuzu.Handlers
<div class="row">
	<div class="span8">
		<div class="hero-unit" id="banner">
		    <a href="/" style="display: inline-block; float: left;"><div id="h1Wrap"></div><div id="truckIcon"></div></a>
            <div id="resTopPhone">@SessionHandler.Dealer.Phone</div>
		</div>
	</div>
	<div class="span8" id="address" style="color: white;">
		<address>
		    <span id="phone"><h2>@SessionHandler.Dealer.Phone</h2></span><br /> 1655 W 6th St. Suite #111<br />Corona, CA 92882
		</address>
	</div>
</div>