FreewayIsuzu/FreewayIsuzu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DapperExtensions;
using FreewayIsuzu.Models;
using vincontrol.Application.ViewModels.CommonManagement;

namespace FreewayIsuzu.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            //var tmp = DapperSqlHelper.GetAll<Models.Entity.Inventory>(Predicates.Field<Models.Entity.Inventory>(f => f.DealerId, Operator.Eq, 37695), new List<ISort>(){ Predicates.Sort<Models.Entity.Inventory>(f => f.InventoryId, true) });
            //var tmp2 = DapperSqlHelper.QueryText<Models.Entity.Inventory>("SELECT TOP 10 * FROM Inventory WHERE DealerId = @DealerId", new {DealerId = 37695});
            return View(@"~/Views/Home/Index.cshtml");
        }

        public ActionResult NewIndex()
        {
            return View(@"~/Views/Home/NewIndex.cshtml");
        }
    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/InventoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using FreewayIsuzu.Handlers;
using FreewayIsuzu.HelperClass;
using vincontrol.Application.Forms.InventoryManagement;
using vincontrol.Constant;
using vincontrol.Data.Model;
using vincontrol.DomainObject;
using vincontrol.Helper;

namespace FreewayIsuzu.Controllers
{
    public class InventoryController : BaseController
    {
        private readonly IInventoryManagementForm _inventoryManagementForm;

        public void Index(string text)
        {
            
        }

        public InventoryController()
        {
            _inventoryManagementForm = new InventoryManagementForm();
        }

        public ActionResult NewCars()
        {
            return View(@"~/Views/Inventory/NewCars.cshtml");
        }

        public ActionResult UsedCars()
        {
            return View(@"~/Views/Inventory/UsedCars.cshtml");
        }

        public ActionResult Detail(string ymm, string vin)
        {
            ViewData["CARTITLE"] = String.Format("{0} {1}", ymm.Replace("-", " "), vin);
            return View(@"~/Views/Inventory/Detail.cshtml");
        }

        public String GetCarDetail(string vin)
        {
            var list = _inventoryManagementForm.GetFullInventoryDetail(SessionHandler.Dealer.DealerId,vin);
            var parser = new JavaScriptSerializer();
            string result = parser.Serialize(list);
            return result;
        }

        public String GetUsedInventory()
        {
            var list = _inventoryManagementForm.GetUsedInventories(SessionHandler.Dealer.DealerId).ToList();
            var parser = new JavaScriptSerializer();
            string result = parser.Serialize(list);
            return result;
        }

        public String GetSimilarMake(string vin, string make)
        {
            var list = _inventoryManagementForm.GetSimilarMake(SessionHandler.Dealer.DealerId, vin, make).ToList();
            var parser = new JavaScriptSerializer();
            string result = parser.Serialize(list);
            return result;
        }

        public String GetSimilarModel(string vin, string model)
        {
            var list = _inventoryManagementForm.GetSimilarModel(SessionHandler.Dealer.DealerId, vin, model).ToList();
            var parser = new JavaScriptSerializer();
            string result = parser.Serialize(list);
            return result;
        }

        public String GetSimilarBodyType(string vin, string body)
        {
            var list = _inventoryManagementForm.GetSimilarBodyType(SessionHandler.Dealer.DealerId, vin, body).ToList();
            var parser = new JavaScriptSerializer();
            string result = parser.Serialize(list);
            return result;
        }

        public String GetNewInventory()
        {
            var list = _inventoryManagementForm.GetNewInventories(SessionHandler.Dealer.DealerId).ToList();
            var parser = new JavaScriptSerializer();
            string result = parser.Serialize(list);
            return result;
        }
      
        public JsonResult LoadSearchConditions()
        {
            var years = _inventoryManagementForm.GetUsedYears(SessionHandler.Dealer.DealerId);
            var makes = _inventoryManagementForm.GetUsedMakes(SessionHandler.Dealer.DealerId);
            var models = _inventoryManagementForm.GetUsedModels(SessionHandler.Dealer.DealerId);

            return Json(new { years, makes, models }, JsonRequestBehavior.AllowGet);
        }

        #region GetFullTextResult

        public class LargeJsonResult : JsonResult
        {
            private const string JsonRequestGetNotAllowed =
                "This request has been blocked because sensitive information could be disclosed to third party web sites when this is used in a GET request. To allow GET requests, set JsonRequestBehavior to AllowGet.";

            public LargeJsonResult()
            {
                MaxJsonLength = Int32.MaxValue;
                RecursionLimit = 10000;
            }

            public int MaxJsonLength { get; set; }
            public int RecursionLimit { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                if (context == null)
                    throw new ArgumentNullException("context");

                if (JsonRequestBehavior == JsonRequestBehavior.DenyGet &&
                    String.Equals(context.HttpContext.Request.HttpMethod, "GET", StringComparison.OrdinalIgnoreCase))
                    throw new InvalidOperationException(JsonRequestGetNotAllowed);

                var response = context.HttpContext.Response;
                response.ContentType = !String.IsNullOrEmpty(ContentType) ? ContentType : "application/json";

                if (ContentEncoding != null)
                    response.ContentEncoding = ContentEncoding;

                if (Data != null)
                {
                    var serializer = new JavaScriptSerializer
                    {
                        MaxJsonLength = MaxJsonLength,
                        RecursionLimit = RecursionLimit
                    };
                    response.Write(serializer.Serialize(Data));
                }
            }
        }

        public ActionResult FullTextSearchWithFullResult(string searchTerm)
        {
            using (var context = new VincontrolEntities())
            {
                var vehicleQuery = GetVehicleQuery(searchTerm, context, QueryBuilderHelper.GetFullTextVehicleQuery);

                var query = string.Format("SELECT * FROM ( {0}) RESULT ORDER BY DealerId, Year DESC, Make, Model, Trim", vehicleQuery.InventoryQuery);

                return new LargeJsonResult
                {
                    Data = BuildFullTextSearchResult(query, context)
                };
            }
        }

        private static VehicleQuery GetVehicleQuery(string searchTerm, VincontrolEntities context, Func<string, List<string>, IEnumerable<int>, string> getQueryFunc)
        {
            var dealerIdList = InventoryQueryHelper.GetDealerList(context).ToList();
            var termList =
                searchTerm.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries).Select(i => i.Trim()).ToList();

            return new VehicleQuery()
            {
                AppraisalQuery = getQueryFunc("AppraisalCar", termList, dealerIdList),
                InventoryQuery = getQueryFunc("InventoryCar", termList, dealerIdList),
                SoldoutQuery = getQueryFunc("SoldoutInventoryCar", termList, dealerIdList)
            };
        }

        private List<VehicleResult> BuildFullTextSearchResult(string query, VincontrolEntities context)
        {
            var result = context.ExecuteStoreQuery<VehicleResult>(query).ToList();

            foreach (var item in result)
            {
                if (item.ThumbnailUrl != null)
                {
                    item.ThumbnailUrl =
                        item.ThumbnailUrl.Split(new[] { ",", "|" }, StringSplitOptions.RemoveEmptyEntries)
                            .FirstOrDefault();
                    item.PhotoUrl = item.ThumbnailUrl;
                }
                else if (item.PhotoUrl != null && item.VehicleStatus != Constanst.VehicleStatus.SoldOut)
                {
                    item.PhotoUrl =
                        item.PhotoUrl.Split(new[] { ",", "|" }, StringSplitOptions.RemoveEmptyEntries)
                            .FirstOrDefault();
                }
                else
                {
                    item.PhotoUrl = item.DefaultStockImage;
                }
            }

            return result;

        }
        #endregion
    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/ServicePartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreewayIsuzu.Controllers
{
    public class ServicePartsController : BaseController
    {
        public ActionResult ServiceInfo()
        {
            return View(@"~/Views/ServiceParts/ServiceInfo.cshtml");
        }
        
        public ActionResult Retail()
        {
            return View(@"~/Views/ServiceParts/Retail.cshtml");
        }
        
        public ActionResult Appointment()
        {
            return View(@"~/Views/ServiceParts/Appointment.cshtml");
        }

        [HttpGet]
        public ActionResult PrintCoupon(string urlImg, string title)
        {
            ViewData["urlImg"] = urlImg;
            ViewData["title"] = title;
            return View(@"~/Views/ServiceParts/PrintCoupon.cshtml");
        }
    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/SpecialsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FreewayIsuzu.Handlers;
using vincontrol.Application.Forms.InventoryManagement;

namespace FreewayIsuzu.Controllers
{
    public class SpecialsController : BaseController
    {
        private readonly IInventoryManagementForm _inventoryManagementForm;

        public SpecialsController()
        {
            _inventoryManagementForm = new InventoryManagementForm();
        }

        public ActionResult VehicleSpecials()
        {
            var list = _inventoryManagementForm.GetFeaturedInventories(SessionHandler.Dealer.DealerId).ToList();
            return View(@"~/Views/Specials/VehicleSpecials.cshtml", list);
        }

        public ActionResult Lease()
        {
            return View(@"~/Views/Specials/Lease.cshtml");
        }

        public ActionResult Service()
        {
            return View(@"~/Views/Specials/Service.cshtml");
        }

        public ActionResult Parts()
        {
            return View(@"~/Views/Specials/Parts.cshtml");
        }
    }
}

FreewayIsuzu/FreewayIsuzu/Controllers/VehicleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FreewayIsuzu.Controllers
{
    public class VehicleController : BaseController
    {
        public ActionResult Value()
        {
            return View(@"~/Views/Vehicle/Value.cshtml");
        }
    }
}

FreewayIsuzu/FreewayIsuzu/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Finding your used and new trucks";
}

@section meta{
    <meta name="description" content="Freeway Isuzu - Finding your used trucks ✓ new trucks ✓ Hundreds of cars for sale ✓ Good prices ✓ Daily updated" />
}

<link type="text/css" rel="stylesheet" href="/Content/css/index.css" />
<link type="text/css" rel="stylesheet" href="/Content/css/responsive.css"/>
<style type="text/css">
    #dealer-info h1 { margin-top: 20px; margin-left: 20px; margin-right: 20px; color: #111111 !important; font-size: 20px; }
    #dealer-info a { color: #111111 !important; font-size: 20px; }

</style>

<script type="text/javascript" src="/Scripts/js/pages/pc_index.js"></script>
<div class="row" id="content">
    <div class="span12">
        <!-- MAIN COLUMN CELL -->
        <div class="row">
            <!-- HERO ROW -->
            <div class="span12">
                <div id="slider">
                    <div id="slider1" style="height: 300px; overflow: hidden;">
                        <div class="sliderImg17" id="sliderImg1">
                            <a href="@Url.Action("Parts","Specials")">
                                <h2>Parts Specials</h2>
                            </a>
                        </div>
                        <div class="sliderImg17" id="sliderImg2">
                            <a href="http://www.isuzutruckparts.net/?refid=70446">
                                <h2>Order Parts!</h2>
                            </a>
                        </div>
                        <div class="sliderImg17" id="sliderImg3">
                            <a href="@Url.Action("NewCars","Inventory")">
                                <h2>New Commercial Vehicles</h2>
                            </a>
                        </div>
                        <div class="sliderImg17" id="sliderImg4">
                            <a href="@Url.Action("Service","Specials")">
                                <h2>Service Specials</h2>
                            </a>
                        </div>
                        <div class="sliderImg17" id="sliderImg5">
                            <a href="@Url.Action("UsedCars","Inventory")">
                                <h2>Pre-Owned Commercial Vehicles</h2>
                            </a>
                        </div>

                        <div class="sliderImg17" id="sliderImg6">
                            <a href="@Url.Action("UsedCars","Inventory")">
                                <h2>Pre-Owned Cars and Trucks</h2>
                            </a>
                        </div>

                        <div class="sliderImg17" id="sliderImg7">
                            <a href="@Url.Action("UsedCars","Inventory")">
                                <h2>Pre-Owned Commercial Vehicles</h2>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END OF HERO ROW -->

        <div class="row">
            <!-- INFO CELL ROW -->
            <div class="span4 cell qlMenus" id="cell1">
                <div id="c1wrap" class="cellwrap qlMenusIn">
                    <h3>Quick Links</h3>
                    <ul class="unstyled">
                        <li>
                            <a class="btn grad-btn success" href="@Url.Action("NewCars","Inventory")">New Inventory</a>
                        </li>
                        <li>
                            <a class="btn grad-btn success" href="@Url.Action("UsedCars","Inventory")">Pre-Owned Inventory</a>
                        </li>
                        <li>
                            <a class="btn grad-btn success" href="@Url.Action("Lease","Specials")">Specials</a>
                        </li>
                        <li>
                            <a class="btn grad-btn success" href="@Url.Action("Value","Vehicle")">Value My Trade</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="span4 cell" id="cell2" style="">
                <div id="c2wrap" class="cellwrap">
                    <h3>Schedule Service!</h3>
                    <p>
                        It has never been easier to schedule service for your Commercial Truck than it is here at Freeway Isuzu! We provide the highest level of service in the industry!
                    </p>
                    <p>
                        Click below to learn more!
                    </p>
                    <a class="btn grad-btn success small more" href="@Url.Action("ServiceInfo","ServiceParts")">More ></a>
                </div>
            </div>
            <div class="span4 cell" id="cell3">
                <div id="c3wrap" class="cellwrap">
                    <h3>Big Thanks!</h3>
                    <p>
                        Freeway Isuzu wants to congratulate Travis N. from Fontana, CA on the purchase of a 2005 Isuzu NPR HD DSL REG! You can be assured that you're driving only the highest quality vehicle in Fontana.
                    </p>
                    <p>
                        Travis N, thank you for your patronage!
                    </p>

                </div>
            </div>
        </div>
        <!-- END OF INFO CELL ROW -->

        <div class="row">
            <div class="span12 cell" id="dealer-info">
                <h1><a href="http://freewayisuzu.com">About Freeway Isuzu</a></h1>
                <p>
                    Freeway Isuzu is a premier medium duty truck dealer with 30 years experience selling trucks in a wide range of models including the NPR, NPR-HD, NQR, NRR and Crew Cab models. The dealership prides itself on the constant  acquisition of premium pre-owned and new Isuzu trucks. We buy right and pass the savings on to you. The staff at Freeway is well versed in the needs of the commercial truck market and can provide nearly every solution to meet your company's needs or requirements be it with commercial vehicles, parts ordering,  service needs and financing opportunities. Thank you for visiting our online inventory or if you want come see us and our showroom in person we'll be happy to welcome you!
                </p>
            </div>
        </div>

        <!-- FOOTER ROW -->
        @{ Html.RenderPartial("~/Views/Shared/_Footer.cshtml"); }
        <!-- END OF FOOTER ROW -->

    </div>
    <!-- END OF MAIN CELL -->
    <div class="span4" id="sidebar">
        <!-- SIDEBAR CELL -->

        <div class="row">
            <!-- SOCIAL MEDIA ROW -->
            <div class="span4" id="social">
                <!-- CONTACT FORM ROW -->
                @{ Html.RenderPartial("~/Views/Shared/_ContactForm.cshtml"); }
							<!-- END OF CONTACT FORM ROW -->

                <div class="fb-like-box" data-href="https://www.facebook.com/pages/Freeway-Isuzu/109055669178685" data-width="232" data-height="454" data-show-faces="false" data-border-color="#ccc" data-stream="true" data-header="false"></div>
            </div>
        </div>
        <!-- END OF SOCIAL MEDIA ROW -->

        <!-- FEATURED VEHICLE ROW -->

        <!-- END OF FEATURED ROW -->

    </div>
    <!-- END OF SIDEBAR CELL -->
</div>
<!-- END OF CONTENT ROW -->
<script type="text/javascript">
    $("div.mn-home").addClass("nav-active");
</script>

FreewayIsuzu/FreewayIsuzu/Views/Home/NewIndex.cshtml
@{
    Layout = "~/Views/Shared/_NewLayout.cshtml";
    ViewBag.Title = "Finding your used and new trucks";
}

@section meta{
    <meta name="description" content="Freeway Isuzu - Finding your used trucks ✓ new trucks ✓ Hundreds of cars for sale ✓ Good prices ✓ Daily updated" />
}

<link type="text/css" rel="stylesheet" href="/Content/css/index.css" />
<link type="text/css" rel="stylesheet" href="/Content/css/responsive.css"/>
<style type="text/css">
    #dealer-info h1 { margin-top: 20px; margin-left: 20px; margin-right: 20px; color: #111111 !important; font-size: 20px; }
    #dealer-info a { color: #111111 !important; font-size: 20px; }

</style>